### ISSUE TITLE
RFC 0016-remove-inline-templates - do not deprecate!

### ISSUE THREAD

**Issue by lauxley** [vuejs/rfcs#155]
(It's not super clear where I should talk about RFCs)

### What problem does this feature solve?
About RFC https://github.com/vuejs/rfcs/blob/master/active-rfcs/0016-remove-inline-templates.md
I don't understand why come back from the very reasonable decision taken in: https://github.com/vuejs/vue/issues/2765.
As stated multiple time before, what makes vue.js so attractive and powerful for us backend developers is that it does not force us into having the logic on the frontend side, or use js tools. The most important for us is the same as everybody else, maintainability, but it means for us that the html has to be in the same place and looks decently nice, which is exactly what inline-template does for us.

> The biggest issue with inline-template is that it makes template scoping very inconsistent.

Nested  scopes/contexts are not inconsistent, they exist in most template languages and make perfect sense (in my opinion).

The  proposed replacements feel like hacks and I personally wouldn't want to use them for everything I do in vue.
I believe a large portion of vue.js user base are backend developers because of this feature, don't make us change framework please..

### What does the proposed API look like?
Don't touch the inline-template api, it works.

**Comment by thecrypticace** [comment]
The point about nested scopes is that they're **not possible** with `inline-template`. As soon as you have an inline template you cannot reference anything from any outer scope.

`inline-template` can be entirely replaced by using v-slot in Vue 3 (and in Vue 2 for the most part as well) and does not have any of the scoping problems but keeps the inline compilation support that `inline-template` provided. I use `v-slot` in place of inline-template in many places due to having a mix of server-rendered and client-side-rendered behavior.

The only thing I've encountered, in Vue 2 at least, when using v-slot as an inline template replacement is that having to manually define a render function w/ all the appropriate props is a bit inconvenient b/c of the need to list computed options explicitly (proxy's can work around this limitation but then you're out for IE 11 support if you need it).

An API made to simplify inline-template -> v-slot scoping at the component level could be a nice transition point. Maybe something like a higher-order component that will handle the edge cases here w/ regards to computed props, injections, etc… I'd also say that w/ the new setup method + composition API + support for returning render functions this is less likely to be necessary but could likely still be wrapped if it proved to provide a better API.

**Comment by yyx990803** [comment]
The ship has already sailed. Reiterating what's been discussed doesn't really make any difference, unless you can provide a reason why the proposed replacements doesn't work for you (on the technical, not personal preference).

**Comment by rrmesquita** [comment]
@yyx990803 just out of curiosity, what was the fundamental reason to drop support for `inline-template`?

I will understand if you say that it brings too much maintenance effort into something that represents a small percentage of the framework's use (even though I believe it's how it's mainly used on traditional server-rendered projects).

The motivation described in [RFC #0016](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0016-remove-inline-templates.md) doesn't seem good enough to remove this feature. If in my project I don't face the mentioned template scoping issue, or even if I do, but I am aware of it and I know how to get around it, shouldn't I be free to choose wether or not I want to use `inline-template` on that specific situation? After all, being able to choose what you think it's best for you is one of Vue's greatest qualities. FYI I'm currently working on a traditional server-rendered project, and I'm using Vue 2 for this very unique reason, and the project looks just like the example I just gave: it's a medium size project with a few dozens of components and I haven't had template scope issues so far.

As for the alternatives, the script template alternative does not work well when the server renders a different markup in each Vue Component usage, because for each component, you can only specify one script template. I can't think of any way around that which is pleasant to go with.

The default slot alternative seems to work well, but it requires you to write the same (small) boilerplate again and again, plus having to either grab all variables you'll use in the template from a master variable (e.g. `<v-contact v-slot="vm">{{ vm.firstName }} {{ vm.lastName }}</v-contact>`) or destruct each of them (e.g. `<v-contact v-slot="{ firstName, lastName }">{{ firstName }} {{ lastName }}</v-contact>`). Yes, I know is not much to write, but again: is it too much work to keep the `inline-template` working in Vue 3? Also, in a quick test project using CDN Vue 3 with this alternative, I kept receiving Vue Warns about properties (`class`, `style` and `key`) being accessed on render while not defined on instance, even though I didn't wrote any of these keywords anywhere, but this is probably due to me binding into the default `<slot v-bind="self" />` a computed variable `self() { return this }`.

You probably do have more reasons to remove it and I would be happy to know them.

I just want to make sure that the team has not overlooked the situation again, and acquire the peace of knowing that it was removed for a reason good enough to go back on [the decision to keep it that you have made in the past](https://github.com/vuejs/vue/issues/2765#issuecomment-215557611).

Thank you for the patience and all the love you've put in this framework.
