### ISSUE TITLE
Advise against Flux, Vuex

### ISSUE THREAD

**Issue by Madyuskin** [vuejs/rfcs#240]
From https://vuex.vuejs.org/#when-should-i-use-it

> If you've never built a large-scale SPA and jump right into Vuex, it may feel verbose and daunting. That's perfectly normal - if your app is simple, you will most likely be fine without Vuex. A simple store pattern (opens new window)may be all you need. But if you are building a medium-to-large-scale SPA, chances are you have run into situations that make you think about how to better handle state outside of your Vue components, and Vuex will be the natural next step for you.

That is wrong and misleading. Every dev team is sure they are going big. Vue is already perfect regardless of the size of an app. Adding Vuex is just harmful. I wrote an article explaining why Flux has nothing to do with Vue:

https://medium.com/@madyuskin/flux-vuex-are-wrong-and-outdated-61438de7c512

I am the author. The same username as on GitHub, I can text you.

**Comment by leopiccionia** [comment]
I think that labeling something upfront "wrong and harmful" may be counter-productive to the debate. ["Considered Harmful" Essays Considered Harmful](https://meyerweb.com/eric/comment/chech.html).

> How can Vuetify thrive without Flux if the latter is so indispensable?

Why should it care about global state management, that's, by definition, orthogonal to component composition?

For component composition, props, events, slots, `provide` and `inject` may be enough. You probably don't need Vuex for that.

> Never used on the server side with Node.js even without immutability

Flux-like patterns are for application-level state management. In a server, you typically want the opposite: the state to be short-lived and isolated by process/request. And most servers already provide mechanisms to encapsulate and pass state, like middlewares.

> It came from React. It didn’t originate in Vue. It is already enough to suspect that something is not right. Flux, Redux were developed because of React’s poor support of immutability.

It sounds like a [genetic fallacy](https://en.wikipedia.org/wiki/Genetic_fallacy) for me. Could you elaborate?

Now for the most interesting part:

> Vue supports immutability for an object reference out of the box

By "immutability for an object reference", you mean object mutability detection, that's what React's diff algorithm actually doesn't handle well.

> That’s why they require you to normalize your state as a SQL database.

The source you're probably quoting recommends normalization because of "nested or relational" data.

For typical nested data, normalization is usually overkill. There are Immer and dozens of other libraries that present solutions for this problem while keeping React/Redux constraints.

Relational data, though, sometimes contain many-to-many dependencies. In those cases, normalization is a better investment. [Normal forms](https://en.wikipedia.org/wiki/Database_normalization) were introduced in 1970 as a method for avoiding data inconsistencies (actual bugs) and duplication. You can obviously handle all cases manually instead of normalizing the data, but bugs may ensue.

Normalizing your data is such a good advice that it appears even outside of the relational databases realm, like in [MongoDB](https://docs.mongodb.com/manual/core/data-model-design/) and [Firebase](https://firebase.google.com/docs/database/ios/structure-data), just to cite two.

It's also important to emphasize that neither Redux nor Vuex strictly require this type of normalization, they're just a mechanism to enforce data consistency.

Theorically, as Vue's diff algorithm detect object mutation (differently from React), you could structure your data to use circular objects (never tried it, so I don't know if Vue is happy with that). But it's still a type of normalization, just different -- and probably harder to enforce. And, differently from "foreign key" normalization, it needs to be made on client-side.

> 1. No v-model support
> 2. Tons of boilerplate. Writing for the sake of writing. Zero commercial value. Wasted time and energy.

[Pathify](https://davestewart.github.io/vuex-pathify/#/) solves these issues very well, while allowing you to use the usual Vuex syntax side-by-side.

---

I'm not disagreeing that Vuex is not always needed. I have worked on many Vue projects that used it, and many that don't.

Vuex greatly helped me maintain and debug code in the past, but I'm glad that the Vue team has some [plans about improving Vuex](https://youtu.be/dQ5btkDrdJ8?t=415) in the next months.

**Comment by Madyuskin** [comment]
Thank you @leopiccionia for your elaborate answer. I am preparing my answer. It might take 2 days.

**Comment by kiaking** [comment]
@Madyuskin I believe it would be better if you could clarify the purpose of this issue 👀 . What is your actual suggestion here? What is the exact thing that you wanna change, add, remove? from what, where, and how?

**Comment by Madyuskin** [comment]
@leopiccionia 
> Why should it care about global state management, that's, by definition, orthogonal to component composition?

I mentioned the absence of Flux in UI widgets in "Why Flux looks suspicious", not in "Why Flux is wrong". If something claims to be:
> predictable, centralized, debuggable, flexible, simple, opinionated, powerful, effective

to be indispensable, and is as popular among developers as Flux, Redux, then I expect such product to be universal. For example, it is just an example, don't come to any conclusion:
<pre>
export default {
  created() {
    this.store = new Vuex.Store({
      ...
    })
  }
}
</pre>
Or be built-in. I am glad Flux is not.
### What is actually Flux?
From https://redux.js.org, the advantages are:
1. Consistent behavior
2. Easy to test
3. Undo/redo
4. State persistence
5. Debuggable
    1. When, where, why, and how your application's state changed
    2. Time-travel debugging
6. Works with any UI layer

All of the above is a result of storing data in global state. It is global state vs local state. You don't need Flux for this. There is only one advantage - ultimate debugging. But why do we need debugging, logging for each a = b, a.push(b), etc? ALL SOFTWARE except some apps that use Flux are written without this level of debugging - operation systems, databases, compilers, drivers, antiviruses, games, everything! And if you do need this level of debugging, then why don't you need this level of debugging in UI widgets? Looks like a bias.

From https://vuejs.org/v2/guide/state-management.html#Simple-State-Management-from-Scratch
> but debugging would be a nightmare.

Note "nightmare". Flux guys always go crazy and hold on tightly to reporting when uncomfortable questions raised. Whole world is programming without this level of debugging. And if other can, and you can't without it, maybe, the problem is not in debugging?

> Normalizing your data is such a good advice

Yes, you are right! Data should always be normalized. But do we need Flux for this? No!
So, what is actually Flux?
<pre>
const counterSlice = createSlice({
  name: 'counter',
  initialState: 0,
  reducers: {
    increment: state => state + 1
  }
})
</pre>
Looks similar to
<pre>
class Counter {
  private int state = 0;
  public void increment() {
    this.state++;
  }
}
</pre>
Firstly, slice and class are incomparable. Moreover, there is no slice in Vuex. Secondly, Flux is a wrap with no purpose. That's why they achieved ultimate debugging and ultimate boilerplate. What is the point of mapping every single method from Array.prototype.* and then repeat it for a new property? If I were paid for the number of lines in code, then OK, I would agree, yeah. And they attributed to a wrap the advantages of normalization and the advantages of keeping everything in global state.
> they're just a mechanism to enforce data consistency.

You are right! Because of global state and normalization. You don't need Flux for this.

> Pathify solves these issues very well, while allowing you to use the usual Vuex syntax side-by-side.

Google: site:vuejs.org Pathify
Any page except forum.vuejs.org and news.vuejs.org?
And you probably already know my answers:
1. No Vuex - no problems
2. Vuex Pathify, Pathify for Vuex Pathify, Pathify for Pathify for Vuex Pathify,...
### The roadmap of Vuex
From https://vuex.vuejs.org/#when-should-i-use-it
> and Vuex will be the natural next step for you.

1. Overall, Vuex is less strict than Redux
2. Unlike Redux, actions doesn't belong to a property
3. Mutations will be removed in Vuex 5
4. ...

You are naturally stepping away from Flux.
### Conclusion
From https://vuex.vuejs.org/#when-should-i-use-it
> if your app is simple, you will most likely be fine without Vuex.

Every dev team is sure they are going big. No money paid for little-to-no work. I think that labeling everyone's apps without Vuex not "fine" upfront may be counter-productive to the project. ["Considered Harmful" Essays Considered Harmful.](https://meyerweb.com/eric/comment/chech.html) That is exactly what happened to me and my team as we had to rewrite our apps without Vuex. I believe this.$root (not even this.$root.$data) is all what we need.

**Comment by Madyuskin** [comment]
Encapsulation should be defined for a class, not for a state.

Wrong:
<pre>
const store = new Vuex.Store({
  state: {
    chats: [{
      id: 1,
      participants: [{
        id: 10,
        name: 'Daniel',
        typing: false
      }, {
        id: 11,
        name: 'Sophia',
        typing: false
      }]
    }]
  },
  mutations: {
    chatParticipantTypingSet(state, payload) {
      const chat = _.find(state.chats, {
        id: payload.chatId
      })

      if (chat) {
        const participant = _.find(chat.participants, {
          id: payload.participantId
        })

        if (participant) {
          participant.typing = payload.typing
        }
      }
    }
  }
})
</pre>

Right:
<pre>
class Chat {
  private List<Participant> participants = new List<Participant>();
  public Participant findParticipantById(string id) {}
}

class Participant {
  private bool typing = false;
  public void setTyping(bool value) {}
}
</pre>

**Comment by Madyuskin** [comment]
I know it might look like "Hey, get rid of Vuex", but the real reason is to help. I don't want beginners to go the trial-and-error path I went:
1. Angular
2. React, Redux
3. Vue, Vuex
4. Vue

Programming must be pleasant. Flux doesn't contribute to it. I have also improved my article and will continue working on the issue:
https://medium.com/@madyuskin/flux-vuex-are-wrong-and-outdated-61438de7c512

**Comment by Madyuskin** [comment]
DavidMulder0 disliked my issue and commented on Medium:

> Do I agree that redux/flux/vuex/etc. aren't always needed? Absolutely. But I also have to say I think it's very misguided to attack it one sidedly. It really does depend on the complexity of the application. Right now I am working on a text editor that uses something like the flux/redux/vuex pattern and it just makes a lot of sense (the 'document' that's getting edited affects the UI in a bunch of different places) and that's not even touching upon how valuable centralized state is for things like 'undo'/'redo' actions or restore functionality when the user leaves an app, but at the same time there is no value at all for certain other applications or just websites. The simplest question to ask yourself I believe is: "Is my application going to have a state that affects things in completely different places in the DOM". In the case of a UI component library this is by definition not the case, so for something like vuetify it doesn't make sense. For something like a complex dynamic batch management interface it might however make the code super easy and clean.

No comments. Flux = Global state. No Flux = No global state.

**Comment by DavidMulder0** [comment]
@Madyuskin The confused reaction just expressed that I am utterly confused by what you're trying to do here. A confused reaction isn't the same thing as a downvote, it's just that none of this makes any sense here. You have been talking with and to yourself for nearly two weeks now. I was fascinated by someone 'attacking' a library I am using, as I enjoy seeing posts of that nature, so I replied to the post. You seemed to be talking about the pattern, but then you attack people for talking about the pattern rather than the libraries, you mix up flux and redux all over your post and that doesn't even touch upon why in the world you would copy a post from Medium to here... maybe the fact that I replied on Medium should have rang a bell that that's where the 'conversation' belonged.

**Comment by Madyuskin** [comment]
@DavidMulder0 I want a comparison in the documentation between Vuex and this.$root. Flux, Vuex are praised one-sidedly.

**Comment by Madyuskin** [comment]
Why must we treat global state as something special? It is the developer, not the library, who determines the state for each component. Neither Flux nor "store pattern" is needed. Please, keep it simple:
### E = mc<sup>2</sup>
If a developer wants complications, it is their decision.

We must resolve the issue ourselves. Please don't borrow anything from Flux, Redux. They have no theory under the hood. "single source of truth" misleads people into treating global state as something special. "local" state has a flaw. Local state isn’t only local if there is a child component. The right naming is as simple as:
1. Parent component
2. Child component
3. The state of a component
4. Global state is the state of the main component

**Comment by Madyuskin** [comment]
### "state management library"
If we compare the size of global state with the size of all local states of a real big and complex application built for a real business. It should be:
### a-bit-of-state management library

**Comment by Madyuskin** [comment]
```JS
export default {
  data: () => ({
  }),
  dataDebug: true, // Enable history of changes to data
  dataDebugSize: 20 // In case of performance issues
  ...
  dataReadOnlyOutside: true // Access restriction. The data can only be changed outside the component via the methods.
}
```
Fluxists and anti-fluxists will be finally united.

**Comment by Madyuskin** [comment]
```JS
import DataUtils from 'vue-data-utils'

export default {
  data: () => ({
  }),
  created() {
    this.dataUtils = new DataUtils(this)
  }
}
```
```C#
abstract class DataUtils {
  abstract public void undo();
  abstract public void redo();
  abstract public void go(int delta);
  ...
}
```
1. A separate package
2. Not mandatory
3. Available to all components
4. We can integrate it into Vue.js devtools
5. Choose your name: Flux, Vuex, DataUtils...
6. Tons of boilerplate is history

@leopiccionia, @kiaking Is something like this possible?

**Comment by Madyuskin** [comment]
https://twitter.com/dan_abramov/status/1191495127358935040

**Comment by Madyuskin** [comment]
We want to keep everything in global state. It is beautiful, has a lot of advantages. With Flux, Vuex comes access restriction — the state can only be changed via the methods. It is useful if we change global state from completely different places. But, almost all time we use and change a part of global state, for example, a Vuex module from the same place.
### /close

**Comment by Madyuskin** [comment]
[The source code of SQLite](https://raw.githubusercontent.com/android/platform_external_sqlite/master/dist/sqlite3.c)
Flux - a variable/property can only be changed via a method.
Now imaging adding Flux.

![st_02_eve](https://user-images.githubusercontent.com/75197252/103007533-a26bd280-4544-11eb-90fe-d996aee191ed.jpg)

Enjoy counters.
