### ISSUE TITLE
Progress of Portal? Here are some suggestions.

### ISSUE THREAD

**Issue by wspl** [vuejs/rfcs#62]
In the early Vue 3.0 trailer, adding Portal component to Vue 3.0 was mentioned. But it seems that the corresponding RFC has not yet been created.

I have a project that is highly dependent on the portal component. Although the portal component is implemented by myself, but the functionality is similar to [portal-vue](https://github.com/linusborg/portal-vue). And encountered some similar problems. I don't know where I can share these issues.

- Breaks provide/inject: https://github.com/LinusBorg/portal-vue/issues/126 .  Portal may cause all mechanisms related to parent-child communication to fail. So it is important to allow mutual access between the portal and the portal-target. And the functions related to communication between the parent and child components also need to take these issues into consideration.

- Vue-devtools support: The actual components that are mounted cannot be displayed in the children scope of portal-target. If there has a redirect or a mirror, it would be great.

Portal is a very useful feature, especially for scenarios like multi-tab code editors. But it requires some underlying compatibility of the framework to work perfectly. I will be very happy to see it become a built-in feature of Vue.

**Comment by LinusBorg** [comment]
You're right, Portals aren't mentioned in any RFC yet (unless I missed something), but the are coming. We already have evaluated the possibilities in our prototyping.

The limitations that you mentioned and we currently see in portal-vue are simply due to missing support for portals on the virtual-dom level. Since in 3.0 we will add Portals to the virtualdom re-implementation, those won't be concerns anymore.

@yyx990803 I think we should decribe how the basic implementation is going to work, maybe in #28 ?

**Comment by yyx990803** [comment]
@LinusBorg I think Portal should have its own RFC since it would be usable in templates too.

**Comment by LinusBorg** [comment]
FYI: I'm currently writing up the RFC for this.

**Comment by dimensi** [comment]
@LinusBorg any news?

**Comment by LinusBorg** [comment]
#112
